server:
  port: ${USER_SERVICE_PORT:8081}

spring:
  datasource:
    url: ${USER_DB_URL:jdbc:postgresql://localhost:5433/user_db}
    username: ${USER_DB_USERNAME:user_app}
    password: ${USER_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

app:
  jwt:
    issuer: ecommerce-user-service
    secret: ${JWT_SECRET}
    access-token-minutes: ${JWT_ACCESS_MINUTES:60}

  admin:
    email: ${APP_ADMIN_EMAIL:}
    password: ${APP_ADMIN_PASSWORD:}

management:
  endpoints:
    web:
      exposure:
        include: health,info